# Generated by Django 4.2.5 on 2023-10-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_chat_messagers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Detils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('user_id', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('cripto_amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('CreatedDate', models.DateTimeField(null=True)),
            ],
        ),
    ]
